// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');
const eslintConfigPrettier = require('eslint-config-prettier');

/** Everything in `packages/spc/src` that `@amk/tokens` may not reach for. */
const SPC_BEYOND_THE_MATHS = [
  '@amk/spc/brr',
  '@amk/spc/driver',
  '@amk/spc/driver-state',
  '@amk/spc/export',
  '@amk/spc/instruments',
  '@amk/spc/layout',
  '@amk/spc/player',
  '@amk/spc/protocol',
  '@amk/spc/wasm-host',
  '@amk/spc/worklet',
];

const FRAMEWORKS = ['@angular/*', '@codemirror/*', '@lezer/*', 'd3', 'd3-*'];

/** A package boundary, stated as a rule rather than as a paragraph. */
const forbid = (patterns, message) => ({
  'no-restricted-imports': ['error', { patterns: [{ group: patterns, message }] }],
});

module.exports = defineConfig([
  {
    ignores: [
      // Reference sources: AddmusicK's C++, gitignored and not ours to lint.
      'AddmusicKsrc/**',
      'AddmusicKreadme/**',
      // Build output.
      'web/dist/**',
      'web/out-tsc/**',
      'web/.angular/**',
      '.selftest/**',
      // Generated by `npm run build:worklet` / `sync-spc-assets` / `generate-git-info`.
      'packages/spc/assets/player/**',
      'web/public/player/**',
      'web/src/app/git-info.generated.ts',
    ],
  },

  // --- Every TypeScript source except the compiler ------------------------
  //
  // The compiler package is deliberately absent: it is a faithful mirror of
  // AddmusicK 1.0.11, and a style rule that asks it to read differently from
  // Music.cpp is a rule working against the point of the file. It gets one
  // block of its own, further down, holding only an import boundary.
  {
    files: [
      'packages/core/**/*.ts',
      'packages/mml-tokens/**/*.ts',
      'packages/spc/**/*.ts',
      'web/src/**/*.ts',
      'scripts/**/*.ts',
    ],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      // `any` was 'warn', but warnings never failed the build, so it was a
      // valve that would have leaked silently. There are none in the tree.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-empty-function': ['error', { allow: ['arrowFunctions'] }],

      // The app ships to a browser: a stray log is a leak, not a diagnostic.
      // `console.error` stays, for the bootstrap failure path in main.ts.
      'no-console': ['error', { allow: ['error'] }],

      // Type-only imports are erased by `isolatedModules`; marking them keeps
      // the runtime import graph honest about what is actually loaded.
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/prefer-readonly': 'error',
      '@typescript-eslint/no-shadow': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      // Discriminated unions are everywhere here — diagnostics, tokens, SPC
      // command kinds — so a new variant nobody handled is a real risk.
      '@typescript-eslint/switch-exhaustiveness-check': 'error',

      // `no-unnecessary-condition` is deliberately NOT enabled. It reads the
      // types, and with `noUncheckedIndexedAccess` off every index access is
      // typed as always-defined — so it flags the real bounds guards this
      // byte-array code is built on as dead. It called all of these unnecessary:
      // `parser.ts` matchWord's `after === undefined` (indexing one past the end
      // of the source), `tokens.ts`'s `LETTER_KINDS[c]` miss, `driver.ts`'s
      // check that a manifest actually defines the requested sample group,
      // `export.ts`'s `match[1] ?? 0` for an optional regex group, and
      // `worklet.ts`'s `outputs[0]` guard. Turning it on would pressure the
      // next reader into deleting guards that fire at runtime.
    },
  },

  // --- Package boundaries -------------------------------------------------
  //
  // This is the only thing holding the dependency graph, and it has to be:
  // npm links every workspace into `node_modules/@amk`, so TypeScript resolves
  // `@amk/spc/driver` from inside `@amk/tokens` perfectly happily however the
  // tsconfigs narrow `paths`. Tested by adding each forbidden import and
  // watching this rule — and only this rule — reject it.
  //
  //   core     → nothing
  //   compiler → core
  //   spc      → core
  //   tokens   → core, and two modules of spc
  {
    files: ['packages/core/**/*.ts'],
    rules: forbid(
      ['@amk/*', ...FRAMEWORKS],
      '@amk/core is the leaf every other package depends on. It depends on nothing.',
    ),
  },
  {
    files: ['packages/mml-compiler/**/*.ts'],
    // The parser, and nothing else. No type-aware rules run here, so there is no
    // program to build — this block exists only to hold the import boundary.
    languageOptions: { parser: tseslint.parser },
    rules: forbid(
      ['@amk/tokens', '@amk/tokens/*', '@amk/spc/*', ...FRAMEWORKS],
      'The compiler is a port of AddmusicK 1.0.11 and reaches for nothing but @amk/core.',
    ),
  },
  {
    files: ['packages/spc/**/*.ts'],
    rules: forbid(
      ['@amk/compiler', '@amk/compiler/*', '@amk/tokens', '@amk/tokens/*', ...FRAMEWORKS],
      'The SPC layer runs in a worklet and depends on nothing but @amk/core.',
    ),
  },
  {
    files: ['packages/mml-tokens/**/*.ts'],
    rules: forbid(
      ['@amk/compiler', '@amk/compiler/*', ...SPC_BEYOND_THE_MATHS, ...FRAMEWORKS],
      'The scanner may read @amk/spc/adsr and @amk/spc/fir — what a byte sounds like — and nothing else.',
    ),
  },

  // --- The Angular application -------------------------------------------
  {
    files: ['web/src/**/*.ts'],
    extends: [angular.configs.tsRecommended],
    processor: angular.processInlineTemplates,
    rules: {
      // Ratchets on behaviour the codebase already has everywhere, so that the
      // conventions in CLAUDE.md stop depending on everyone having read it.
      '@angular-eslint/prefer-signals': 'error',
      '@angular-eslint/no-uncalled-signals': 'error',
      '@angular-eslint/computed-must-return': 'error',
      '@angular-eslint/prefer-service-decorator': 'error',
      '@angular-eslint/prefer-output-readonly': 'error',
      '@angular-eslint/consistent-component-styles': 'error',
      '@angular-eslint/no-duplicates-in-metadata-arrays': 'error',
      '@angular-eslint/use-component-selector': 'error',
      '@angular-eslint/inject-at-top': 'error',
      '@angular-eslint/no-developer-preview': 'error',
      '@angular-eslint/no-experimental': 'error',

      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'amk',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: ['element', 'attribute'],
          prefix: 'amk',
          style: 'kebab-case',
        },
      ],
    },
  },

  {
    // CLI test harnesses (npm run selftest/spctest/...) print by design.
    files: ['scripts/**/*.ts', 'scripts/**/*.mjs'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // Node scripts and this config itself: no TypeScript project to resolve,
    // so the type-aware rules above do not apply.
    files: ['**/*.js', '**/*.mjs'],
    extends: [eslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'commonjs',
      globals: { __dirname: 'readonly', module: 'writable', require: 'readonly' },
    },
  },
  {
    files: ['**/*.mjs'],
    languageOptions: { sourceType: 'module' },
  },

  // --- Templates ----------------------------------------------------------
  //
  // `templateAccessibility` is deliberately absent: this project ships no ARIA
  // attributes and no `role`/`tabindex`, by decision rather than by oversight.
  // See the accessibility note in CLAUDE.md.
  {
    files: ['web/src/**/*.html'],
    extends: [angular.configs.templateRecommended],
    rules: {
      '@angular-eslint/template/prefer-self-closing-tags': 'error',
      '@angular-eslint/template/prefer-at-else': 'error',
      '@angular-eslint/template/prefer-at-empty': 'error',
      '@angular-eslint/template/prefer-contextual-for-variables': 'error',
      '@angular-eslint/template/prefer-class-binding': 'error',
      '@angular-eslint/template/prefer-static-string-properties': 'error',
      '@angular-eslint/template/prefer-template-literal': 'error',
      '@angular-eslint/template/prefer-built-in-pipes': 'error',
      '@angular-eslint/template/require-switch-default': 'error',
      '@angular-eslint/template/no-empty-control-flow': 'error',
      '@angular-eslint/template/no-non-null-assertion': 'error',
      '@angular-eslint/template/attributes-order': 'error',

      // Two rules are deliberately absent because everything they flag here is
      // correct:
      //
      // `no-duplicate-attributes` reads `class="..."` next to `[class]="..."`
      // as one attribute written twice. To Angular they are a static attribute
      // and a class-map binding, and it merges them — which is exactly how the
      // ARAM swatches and diagnostic severities set layout statically and
      // colour dynamically.
      //
      // `button-has-type` cannot see through a component. Every `<button
      // amk-button>` already gets `type="button"` from Button's host binding
      // (shared/button/button.ts), so the rule found sixteen buttons and only
      // one of them — a raw `<button>` in the changelog trigger, now fixed —
      // was actually missing a type.

      // Styling is Tailwind utility classes throughout; an inline style is a
      // theme variable that escaped styles.css. `[style.x.px]` bindings, which
      // the ARAM bar needs for geometry, are not what this rule means.
      '@angular-eslint/template/no-inline-styles': ['error', { allowBindToStyle: true }],

      // `no-call-expression` would be the rule that catches work done per row
      // per change-detection pass — the sample browser's decode-the-whole-
      // library bug was exactly its target. It cannot be used here: it matches
      // every `Call` node in a template, and in a signals codebase every read
      // is one. It reports 178 problems, and the first is
      // `library.overrideCount() > 0`. Its `allowList`/`allowPrefix` options
      // match on the callee's name, and nothing in a name distinguishes a
      // signal from a method.
      //
      // So that class of bug is kept out structurally instead: panels build a
      // `computed` of view models with everything resolved — see the `rows` in
      // sample-browser.ts, aram-budget.ts and stats-grid.ts — rather than
      // calling a method per row.
    },
  },

  eslintConfigPrettier,
  {
    // Every block is braced, and every block is followed by a blank line.
    //
    // Prettier cannot express either half: it never adds or removes braces, and
    // it never inserts blank lines, only collapses runs of them to one. So this
    // is the one place where layout is a lint rule rather than a formatter
    // setting — and it has to sit *after* eslintConfigPrettier, which lists
    // `curly` among the rules it switches off. Set earlier, it would be turned
    // back off by the last element of this array and pass for the wrong reason.
    //
    // `packages/mml-compiler` is not listed, for the same reason it is absent
    // from the block at the top of this file.
    files: [
      'packages/core/**/*.ts',
      'packages/mml-tokens/**/*.ts',
      'packages/spc/**/*.ts',
      'web/src/**/*.ts',
      'scripts/**/*.ts',
      '**/*.js',
      '**/*.mjs',
    ],
    rules: {
      // `all` is also the only form that is safe next to Prettier: the
      // `multi-line` and `multi-or-nest` options argue with it about wrapping.
      curly: ['error', 'all'],

      // `block-like` is any statement ending in `}`, so this covers if/else,
      // for, while, switch and try, and leaves `const x = computed(() => {…});`
      // alone. Nothing is required before a closing brace, so a block that ends
      // its function needs no trailing blank line.
      //
      // Deprecated out of ESLint core in 8.53 and rehomed in @stylistic, but it
      // still ships in ESLint 10 and runs without a warning. If a future major
      // drops it, that surfaces as an unknown-rule error rather than as silence.
      'padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: 'block-like', next: '*' },
      ],
    },
  },
]);
